### PR TITLE
OpenSSL 1.1.1 w/ TLSv1.3 support

### PR DESCRIPTION
**Pull request by OhHeyAlan**
Remove OpenSSL from Debian repo and adds OpenSSL 1.1.1 from source

### CODE REVIEW

**Comment by jc21** [comment]
Thanks for the contribution. My only suggestion is to split up the building and the final image, [here's an example](https://github.com/jc21/nginx-proxy-manager-base/blob/master/Dockerfile.arm64). This will reduce the final image size by not baking in the building programs.

**Comment by OhHeyAlan** [comment]
Step 8/20 : ADD dist                /app/dist
ADD failed: stat /var/lib/docker/tmp/docker-builder789719102/dist: no such file or directory

**Comment by OhHeyAlan** [comment]
I see what you mean now!

**Comment by jc21** [comment]
Yep :) Having issues getting the arm images to build but once they're sorted I'll push the change upstream to the main app.

**Pull request closed without merging**
